### PR TITLE
Feature/26381 - property sets made accessible everywhere

### PR DESCRIPTION
**Pull request by rubychrstn**
In this PR, article property sets are made accessible overall in topseller, similar products and bought articles in addition to existing listing properties

### CODE REVIEW

**Comment by hrombach** [comment]
I made a few optimizations and removed the service decoration because it was changing the method signature imposed by the interface too much. I also do not believe it was necessary after all because there is a discrete service that returns article properties already.

**Comment by hrombach** [comment]
I will do some additional tests tomorrow before merging this PR.

**Comment by hrombach** [comment]
@sbrueggenolte would you do a quick code check too, just to make sure I'm not breaking the plugin? :wink:

**Comment by tpierschel** [comment]
it's unbreakable :-)

**Pull request merged**
